### ISSUE TITLE
Upbase Neue: bower.json preparedness and versioning

### ISSUE THREAD

**Issue by jvlahos** [Upstatement/upbase#29]
- Read #26. Look around the `upbase-neue` branch and see whatcha think. Any comments, ideas, questions or concerns, let me know! 
- Fork the `upbase-neue` branch and call it `upbase-neue-mb` or something. Submit any contributions as a pull request and assign to me.
- Make Upbase Neue more up-to-snuff with being listed in the Bower registry. Also see how our versioning system is holding up and what a good plan and workflow for v1.0.0 release, deprecation-warning releases, and future releases would look like.

**Comment by mgburns** [comment]
Looking good, @jvlahos! I've branched [upbase-neue-mgburns](https://github.com/Upstatement/upbase/tree/upbase-neue-mgburns) off of [upbase-neue](https://github.com/Upstatement/upbase/tree/upbase-neue) to hold my thoughts. PR en route!

**Comment by mgburns** [comment]
I've just submitted a [PR](https://github.com/Upstatement/upbase/issues/30) with some updates to `bower.json` and `README.md`. Regarding versioning / backwards compatibility -- I think we should follow [semantic versioning](http://semver.org/). Next steps:

* Create a new minor release (0.2.0) with deprecation notices / communicating upcoming changes in the next major release.
* Create a new major release (1.0.0) removing the deprecated functions.
* Add migration notes for those looking to upgrade.
* Register as Bower package.

One thing worth mentioning for projects curently managing Upbase as a dependency using Bower:

If they are referencing this repository __without__ a specific version fragment (e.g. `git@github.com:Upstatement/upbase.git` instead of `git@github.com:Upstatement/upbase.git#~0.1.4`) they __will__ be upgraded the next time anyone runs `bower install` or `bower update`. We should communicate this as part of the 0.2.0 release so that those that are not ready to upgrade can update their `bower.json` files accordingly.

**Comment by mgburns** [comment]
Closing this issue as we're moving the `upbase-neue` branch to a separate repository. Will define release process and publish to Bower from there.
